name: My First Action
on: push
jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run:
          echo "$GITHUB_REPOSITORY"
      - name: Step 2
        run:
          echo "${{ secret.TEST_SECRET }}"
        
